= MV-Util

image::https://drone.proximyst.com/api/badges/Minevictus/MV-Util/status.svg[link="https://drone.proximyst.com/Minevictus/MV-Util"]

A utility plugin for both Spigot and BungeeCord for Minevictus.

== Build

Requirements:

. Java 8-14 JDK.

Method:

. Execute `./gradlew shadowJar`.
. Find the jars in `build/libs`.

== Usage

Plop the respective jars into their respective `plugins` directories.

The plugins are support being unloaded and loaded at will using Plugman or something alike on BungeeCord.

== Depend

Both versions require the following repository:

[source,xml]
----
<repositories>
  <repository>
    <id>proxi-nexus</id>
    <url>https://nexus.proximyst.com/repository/maven-public/</url>
  </repository>
</repositories>
----

[source,kotlin]
----
repositories {
    maven {
        name = "proxi-nexus"
        // Groovy DSL does not require the `uri` call.
        url = uri("https://nexus.proximyst.com/repository/maven-public/")
    }
}
----

== Spigot

Current version:

image:https://img.shields.io/github/release/Minevictus/MV-Util.svg[Releases, link=https://github.com/Minevictus/MV-Util/releases/]

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>us.minevict.mvutil</groupId>
    <artifactId>spigot</artifactId>
    <version>insert here</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
----

[source,kotlin]
----
dependencies {
    compileOnly("us.minevict.mvutil:spigot:insert here")
}
----

`plugin.yml`:

[source,yaml]
----
depend: [MV-Util]
----

`minecrell/plugin-yml`:

[source,kotlin]
----
bukkit {
    depends = listOf("MV-Util")
}
----

== BungeeCord

Current version: 

image:https://img.shields.io/github/release/Minevictus/MV-Util.svg[Release, link=https://github.com/Minevictus/MV-Util/releases/]

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>us.minevict.mvutil</groupId>
    <artifactId>bungee</artifactId>
    <version>insert here</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
----

[source,kotlin]
----
dependencies {
    compileOnly("us.minevict.mvutil:bungee:insert here")
}
----

`bungee.yml`:

[source,yaml]
----
depends: [MV-Util]
----

`minecrell/plugin-yml`:

[source,kotlin]
----
bungee {
    depend = setOf("MV-Util")
}
----

== Configuration

=== Database Configuration
Plugins can inherit all the values required to connect to a SQL database
by pulling the values from MV-Utils.

They can, however, specify different values in their own TOML config files.
These nodes are called:

* database-name _(default: Mv-Util's prefix concat lowercase plugin name)_.
** SQL database name we want to connect to.

* database-username _(default: Mv-Util's SQL username)_.
** SQL user with read/write access to the database.

* database-password _(default: Mv-Util's SQL password)_.
** Password for the user specified above.

* database-host-and-port _(default: Mv-Util's SQL host and port)_
** Host and port (a.k.a. address) of the SQL database.
